#!/bin/bash

usage() {
	echo "usage: checker <file> <class>"
	exit 1
}

if [ $# -lt 2 ] ; then
	usage
fi

echo hi

FILE=`redis-cli ISMEMBER "relocated:processed $1"`
if [ $? -eq 0 ] ; then
	exit 1
fi

exit 0
