#!/bin/bash

touch_file() {
  touch "${TMPDIR}"/$1/$2
}

loop_it() {
  i=0
  while [ ${i} -lt $1 ] ; do
    echo "hello" >> "${TMPDIR}"/$2/$3
    sleep 1
    i=$((i+1))
  done
}

usage() {
  echo "Make sure relocated is running: node relocated.js"
  exit 1
}

if ! pgrep -f relocated ; then
  usage
fi

echo "Running a little test"

TMPDIR="tmp_relocated"
mkdir -p "${TMPDIR}" "${TMPDIR}"/images "${TMPDIR}"/logs "${TMPDIR}"/movies "${TMPDIR}"/misc "${TMPDIR}"/images/processed_images

while true ; do (sleep 4; touch_file images $RANDOM.jpg) ; done &

(while true ; do
  loop_it 10 movies $RANDOM.mov
done
) &

(while true ; do
loop_it 12 logs $RANDOM.log
done) &
